export const CREATED_STATUS = 201;
export const ERROR_SERVER_STATUS = 500;
export const INVALID_REQUEST_STATUS = 400;
export const BAD_CREDENTIALS_STATUS = 401;
export const BAD_REQUEST_STATUS = 422;
export const OK_STATUS = 200;
export default {
  OK_STATUS,
  CREATED_STATUS,
  ERROR_SERVER_STATUS,
  INVALID_REQUEST_STATUS,
};
